/*
  Generate the kernel for surface expansions of the phase space characteristics.

  The functions called in this file are in gkFuncs-alpha-surf.mac.
*/
load("gk_collisionless/gk_collisionless_flux-surf-conf")$
load("gk_collisionless/gk_collisionless_flux-surf-vpar")$

/* ...... USER INPUTS........ */

/* Serendipity basis. */
minPolyOrder_Ser : 1$
maxPolyOrder_Ser : 1$
minCdim_Ser : 1$
maxCdim_Ser : 3$

/* Tensor order basis. No need to generate p=1. */
minPolyOrder_Tensor : 2$
maxPolyOrder_Tensor : 2$
minCdim_Tensor : 1$
maxCdim_Tensor : 0$

/* ...... END OF USER INPUTS........ */

/* Vdim possibilities for each of Cdim=[1,2,3]. */
gkVdims : [[1,2], [2], [2]]$

/* To generate other bases, just add corresponding column to arrays below. */
bName        : ["ser", "tensor"]$
minPolyOrder : [minPolyOrder_Ser, minPolyOrder_Tensor]$
maxPolyOrder : [maxPolyOrder_Ser, maxPolyOrder_Tensor]$
minCdim      : [minCdim_Ser, minCdim_Tensor]$
maxCdim      : [maxCdim_Ser, maxCdim_Tensor]$

clabels : ["x","y","z"]$
vlabels : ["vpar","mu"]$

/* Boundary side and type. */
bound_side : ["lower","upper"]$
bound_type : ["periodic","nonperiodic","multib"]$

/* Options for writing kernels with and without toroidal field (b_y=0), one per dimension. */
byOpt : [[false], [false, true], [false, true]]$
byStr : ["", "_no_by"]$

/* Generate kernels of selected types. */
for bInd : 1 thru length(bName) do (
  for c : minCdim[bInd] thru maxCdim[bInd] do (
    for gkV : 1 thru length(gkVdims[c]) do (
      v : gkVdims[c][gkV],

      maxPolyOrderB : maxPolyOrder[bInd],
      if (c=3) then maxPolyOrderB : 1, /* Only generate p=1 kernels for 3x2v */

      for polyOrder : minPolyOrder[bInd] thru maxPolyOrderB do (
        for byI : 1 thru length(byOpt[c]) do (
          no_by : byOpt[c][byI],
          no_byStr : byStr[byI],

          /* Interior conf-space kernels. */
          is_bound : false,
          for dir : 1 thru c do (
            fname : sconcat("~/max-out/gk_collisionless_flux_surf",clabels[dir],no_byStr,"_", c, "x", v, "v_", bName[bInd], "_p", polyOrder, ".c"),
            disp(printf(false,"Creating flux surf~a ~a file: ~a",clabels[dir],no_byStr,fname)),
      
            fh : openw(fname),
            printf(fh, "#include <gkyl_gk_collisionless_flux_kernels.h> ~%"),
  
            funcName : sconcat("gk_collisionless_flux_surf",clabels[dir],no_byStr,"_", c, "x", v, "v_", bName[bInd], "_p", polyOrder),
            buildGKFluxConfESKernel(dir, fh, funcName, c, v, bName[bInd], polyOrder, no_by, is_bound, "", ""),
            close(fh)
          ),

          /* Boundary conf-space kernels. */
          is_bound : true,
          for tI : 1 thru length(bound_type) do (

            for dir : 1 thru c do (
              fname : sconcat("~/max-out/gk_collisionless_flux_boundary_surf",clabels[dir],no_byStr,"_",bound_type[tI],"_", c, "x", v, "v_", bName[bInd], "_p", polyOrder, ".c"),
              disp(printf(false,"Creating flux boundary file: ~a",fname)),
      
              fh : openw(fname),
              printf(fh, "#include <gkyl_gk_collisionless_flux_kernels.h> ~%"),
  
              for sI : 1 thru length(bound_side) do (
                funcName : sconcat("gk_collisionless_flux_boundary_surf",clabels[dir],no_byStr,"_",bound_side[sI],"_",bound_type[tI],"_", c, "x", v, "v_", bName[bInd], "_p", polyOrder),
                buildGKFluxConfESKernel(dir, fh, funcName, c, v, bName[bInd], polyOrder, no_by, is_bound, bound_side[sI], bound_type[tI])
              ),
              close(fh)
            )
          ),

          /* Surface flux in vparallel direction.*/
          fname : sconcat("~/max-out/gk_collisionless_flux_surf",vlabels[1],no_byStr,"_", c, "x", v, "v_", bName[bInd], "_p", polyOrder, ".c"),
          disp(printf(false,"Creating flux surfvpar file: ~a",fname)),
  
          fh : openw(fname),
          printf(fh, "#include <gkyl_gk_collisionless_flux_kernels.h> ~%"),

          funcName : sconcat("gk_collisionless_flux_surf",vlabels[1],no_byStr,"_", c, "x", v, "v_", bName[bInd], "_p", polyOrder),
          buildGKFluxVparESKernel(c+1, fh, funcName, c, v, bName[bInd], polyOrder, no_by, false),
          close(fh)
        )
      )
    )
  )
)$
