load("core/modal-basis.mac") $

load("core/recovery-calc/recovery-1cell.mac") $
load("core/recovery-calc/recovery-2cell.mac") $
load("core/recovery-calc/recovery-3cell.mac") $
load("core/recovery-calc/recovery-face.mac") $

/* -- Helper Functions -------------------------------------------- */

etaDir(dir, xc, dx, fn) := block(
  /* A helper function to shift basis functions in only one direction.
     Example: etaDir(y, dy/2, dy, fn) */
  return(subst(td=dir, subst(dir=2*(td-xc)/dx, fn)))
) $

eta(vars, xc, dx, fn) := block([out],
  /* A helper function to shift basis functions in all directions
     together
     Example: eta([dx/2, -dy/2], [dx, dy], fn) */
  out : etaDir(vars[1], xc[1], dx[1], fn),
  for d : 2 thru length(vars) do (
    out : etaDir(vars[d], xc[d], dx[d], out)
  ),
  return(out)
) $

getDirs(numDims, polyOrder) := block(
  [dirs, varsC, basisC, varsP, basisP, basisConstant],
  if (numDims < 4) then (
    load(sconcat("core/basis-precalc/basisSer", numDims, "x", ".lisp"))
  ) else (
    load(sconcat("core/basis-precalc/basisSer", numDims-3, "x", 3, "v", ".lisp"))
  ),
  if polyOrder > 0 then (
    dirs : if (numDims<4) then varsC else varsP
  ) else (
    dirs : 1
  ),
  return(dirs)
)$
